---
example-posttype:
  labels:
    name: Example Post Types
    singular_name: Example Post Type
    menu_name: Example Post Types
    name_admin_bar: Example Post Types
    add_new: Add New
    add_new_item: Add New Example Post Type
    edit_item: Edit Example Post Type
    new_item: New Example Post Type
    view_item: View Example Post Type
    search_items: Search Example Post Types
    not_found: No Example Post Types found
    not_found_in_trash: No Example Post Types found in trash
    all_items: All Example Post Types
    parent_item: Parent Example Post Type
    parent_item_colon: 'Parent Example Post Type:'
    archive_title: Example Post Types
  description: Example Post Type Description
  public: true
  publicly_queryable: true
  exclude_from_search: false
  show_in_nav_menus: false
  show_ui: true
  show_in_menu: true
  show_in_admin_bar: true
  menu_position:
  menu_icon: dashicons-admin-site
  can_export: true
  delete_with_user: false
  hierarchical: false
  has_archive: example_post_type
  query_var: example_post_type
  capability_type: page
  map_meta_cap: true
  rewrite:
    slug: example-posttype
    with_front: false
    pages: true
    feeds: true
    ep_mask: 1
  supports:
  - custom-fields
  - revisions
  - title
